func foo() {
    throw "x";
}

try {
    foo();
} catch {
    Console.WriteLine("caught"); // Expected: caught
}
